name: Test
on: push
jobs:
  build:
    strategy:
      matrix:
        kind: ['alpine', 'centos', 'debian', 'ubuntu', 'amazonlinux1']
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build Docker Image
      run: |
        docker build -f ${{ matrix.kind }}.dockerfile -t ${{ matrix.kind }} .
        docker run -t ${{ matrix.kind }}
